name: Test pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "*"
  workflow_dispatch:
    inputs:
      environment:
        description: "Selecciona el entorno"
        required: false
        type: choice
        default: 'pro'
        options:
          - dev
          - pro
      job-to-run:
        description: "Job to run"
        required: false
        type: choice
        default: 'job3'
        options:
          - job1
          - job2
          - job3

permissions:
  contents: write

jobs:
  job1:
    name: job1
    # runs-on: babyrunner
    runs-on: ubuntu-latest
    container:
      image: ubuntu:22.04
    steps:
      - name: Obtain Latest Git ONLY within container for checkout
        run: |
          sleep 3
          apt-get update
          apt-get install -y git
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Step 1 - ejecucion
        run: |
          git config --global user.name "alexmllo"
          git config --global user.email "alex.mitjans@ithinkupc.com"
          echo "Hello World" > test.txt
          #git config --global --add safe.directory /__w/test-pipelines/test-pipelines
          git add test.txt
          git commit -m "Add test file"
          git push
  job2:
    name: job2
    if: ${{ github.event_name == 'pull_request' }}
    needs: job1
    runs-on: ubuntu-latest
    container:
      image: ubuntu:22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Step 2 - ejecucion
        run: echo "Ejecutando step2"
  job3:
    name: job3
    if: ${{ github.event_name == 'push' }}
    needs: job1
    runs-on: ubuntu-latest
    container:
      image: ubuntu:22.04
    steps:
      - name: Check entorno
        if: ${{ github.event_name == 'push'}}
        run: echo "En entorno production"
      - name: Finalizacion
        run: |
          sleep 3
          echo "Pipeline completa despues de step2 y step3"
