name: Test pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "*"
  workflow_dispatch:
    inputs:
      environment:
        description: "Selecciona el entorno"
        required: false
        type: choice
        default: 'dev'
        options:
          - dev
          - pro
      job-to-run:
        description: "Job to run"
        required: false
        type: choice
        default: 'step3'
        options:
          - step1
          - step2
          - step3

jobs:
  step1:
    name: step1
    if: ${{ github.event.inputs.job-to-run == 'step1' }}
    # runs-on: babyrunner
    runs-on: ubuntu-latest
    container:
      image: ubuntu:22.04
    steps:
      - name: Obtain Latest Git ONLY within container for checkout
        run: |
          sleep 3
          apt-get update
          apt-get install -y git
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Step 1 - ejecucion
        run: |
          pwd
          ls -la
          #echo "Hello World" > test.txt
          #git add test.txt
          #git commit -m "Add test file"
          #git push
  step2:
    name: step2
    if: ${{ github.event.inputs.job-to-run == 'step2' }}
    needs: step1
    runs-on: ubuntu-latest
    container:
      image: ubuntu:22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Step 2 - ejecucion
        run: echo "Ejecutando step2"
  step3:
    name: step3
    if: ${{ github.event.inputs.job-to-run == 'step3' }}
    # needs: step1
    runs-on: ubuntu-latest
    container:
      image: ubuntu:22.04
    steps:
      - name: Check entorno
        if: ${{ inputs.environment == 'pro' }}
        run: echo "En entorno production"
      - name: Finalizacion
        run: |
          sleep 3
          echo "Pipeline completa despues de step2 y step3"
